module.exports = {
    ERROR_MES : 'I couldn\'t fetch your request. Please try again',
    CONTEXT_LOC : 'loc',
    CONTEXT_WEATHER: 'weather',
    // outfits
    COLD_WEATHER : [
        'wool socks',
        'wool cap',
        'turtleneck',
        'thermal pants',
        'sweatshirt',
        'sweatpants',
        'sweater',
        'snowboard pants',
        'ski pants',
        'shawls',
        'scarf',
        'jumper',
        'balaclava',
        'beanie',
        'boots',
        'cardigan',
        'fleece top',
        'gloves',
        'jacket'
    ],
    WARM_WEATHER : [
        'tennis shoes',
        'lounge wear',
        'socks',
        'sneakers',
        'sleeve shirt',
        'casual shirt',
        'coat',
        'dress pants',
        'dress shirt',
        'dress',
        'gum boots',
        'hat',
        'hoodie',
    ],
    HOT_WEATHER : [
        'tank top',
        't-shirt',
        'shirt',
        'swimwear',
        'swim goggles',
        'sunscreen',
        'skirt',
        'shorts',
        'bathing suit',
        'bra',
        'capri',
        'flips flops',
        'pool shoes',
        'sandals',
        'slippers',
    ],
    UNKNOWN_WEATHER : [
        'underwear',
        'tie',
        'neck gaiter',
        'pajama',
        'sleepwear',
        'suit',
    ],
    RAIN : [
        'umbrella',
        'coat',
        'gum boots',
        'hat',
        'jacket',
        'rain coat',
        'rain jacket',
        'rain pants',
    ],
    SNOW : [
        'gloves',
        'fleece top',
        'ski pants',
        'snowboard pants',
    ],
    SUN : [
        'swimwear',
        'swim goggles',
        'bra',
        'bathing suit',
        'flips flops',
        'sandals',
        'sunglasses',
        'sunscreen',
    ],
    OUTFIT_YES : [
        'That would be a good idea.',
        'Sure.',
        'Yeah, why not.',
        'Considering the forecast, I\'m going to say yes.'
    ],
    OUTFIT_NO : [
        'No, I don\'t think so.',
        'I don\'t think that will be necessary.',
        'You can bring it if you like, but I doubt you\'ll need it.',
        'It seems pretty unlikely you\'ll need that.'
    ]
};